//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RT.DL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Authorization
    {
        public int AuthorizationId { get; set; }
        public Nullable<int> fkCustomerId { get; set; }
        public string Director1Name { get; set; }
        public string Director2Name { get; set; }
        public string Director3Name { get; set; }
        public string BranchHead { get; set; }
        public string MBoyBranch { get; set; }
        public string MarketBoy1 { get; set; }
        public string MarketBoy2 { get; set; }
        public string MarketBoy3 { get; set; }
    
        public virtual Customer Customer { get; set; }
    }
}
