//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RT.DL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CollectionEntryDetail
    {
        public int CollectionEntryDetailId { get; set; }
        public Nullable<int> fkCollectionEntryId { get; set; }
        public string RefType { get; set; }
        public string RefNumber { get; set; }
        public Nullable<System.DateTime> RefDate { get; set; }
        public Nullable<decimal> RefAmount { get; set; }
        public Nullable<decimal> Discount { get; set; }
        public Nullable<decimal> GR { get; set; }
        public Nullable<decimal> AdjustedAmount { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    
        public virtual CollectionEntry CollectionEntry { get; set; }
    }
}
