//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RT.DL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CollectionEntry
    {
        public CollectionEntry()
        {
            this.CollectionEntryDetails = new HashSet<CollectionEntryDetail>();
        }
    
        public int CollectionEntryId { get; set; }
        public string IsLocked { get; set; }
        public Nullable<System.DateTime> DraftReceiptDate { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
        public Nullable<bool> IsDirect { get; set; }
        public Nullable<bool> IsReturnedDraft { get; set; }
        public Nullable<int> fkCustomerId { get; set; }
        public Nullable<int> fkSupplierId { get; set; }
        public Nullable<int> fkBankId { get; set; }
        public Nullable<int> fkCourierId { get; set; }
        public string Source { get; set; }
        public string DraftOrCashOrCheque { get; set; }
        public string DDOrChequeNumber { get; set; }
        public Nullable<System.DateTime> DDOrChequeDate { get; set; }
        public Nullable<decimal> DraftAmount { get; set; }
        public string IsCommissionReceived { get; set; }
        public string DDPrintedOnCoverNumber { get; set; }
        public string IsPrintDetails { get; set; }
        public string IsPrintAdjustments { get; set; }
        public Nullable<int> NoOfCopies { get; set; }
        public string Remark { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual MstBank MstBank { get; set; }
        public virtual MstCourier MstCourier { get; set; }
        public virtual Supplier Supplier { get; set; }
        public virtual ICollection<CollectionEntryDetail> CollectionEntryDetails { get; set; }
    }
}
