//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RT.DL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public Customer()
        {
            this.Authorizations = new HashSet<Authorization>();
            this.CustomerContactInfoes = new HashSet<CustomerContactInfo>();
            this.CustomerInfoes = new HashSet<CustomerInfo>();
            this.CustomerProprietors = new HashSet<CustomerProprietor>();
            this.CustomerSalesmen = new HashSet<CustomerSalesman>();
            this.CustomerSisterConcerns = new HashSet<CustomerSisterConcern>();
            this.OrderEntries = new HashSet<OrderEntry>();
            this.Parties = new HashSet<Party>();
            this.References = new HashSet<Reference>();
            this.CustomerAccountants = new HashSet<CustomerAccountant>();
            this.OrderTransactions = new HashSet<OrderTransaction>();
            this.SaleLREntries = new HashSet<SaleLREntry>();
        }
    
        public int CustomerId { get; set; }
        public string CustomerACNumber { get; set; }
        public Nullable<int> fkCreatedByBranchId { get; set; }
        public string CashOrCredit { get; set; }
        public string CustomerName { get; set; }
        public string Alias { get; set; }
        public string TypeOfFirm { get; set; }
        public string Priority { get; set; }
        public string Status { get; set; }
        public string TIN { get; set; }
        public string CSTNumber { get; set; }
        public string GSTNumber { get; set; }
        public string Password { get; set; }
        public string LastOAC { get; set; }
        public Nullable<int> NoLRAddressPrinting { get; set; }
        public Nullable<int> fkSubAgentId { get; set; }
        public string Zone { get; set; }
        public string Group { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    
        public virtual ICollection<Authorization> Authorizations { get; set; }
        public virtual MstBranch MstBranch { get; set; }
        public virtual MstSubAgent MstSubAgent { get; set; }
        public virtual ICollection<CustomerContactInfo> CustomerContactInfoes { get; set; }
        public virtual ICollection<CustomerInfo> CustomerInfoes { get; set; }
        public virtual ICollection<CustomerProprietor> CustomerProprietors { get; set; }
        public virtual ICollection<CustomerSalesman> CustomerSalesmen { get; set; }
        public virtual ICollection<CustomerSisterConcern> CustomerSisterConcerns { get; set; }
        public virtual ICollection<OrderEntry> OrderEntries { get; set; }
        public virtual ICollection<Party> Parties { get; set; }
        public virtual ICollection<Reference> References { get; set; }
        public virtual ICollection<CustomerAccountant> CustomerAccountants { get; set; }
        public virtual ICollection<OrderTransaction> OrderTransactions { get; set; }
        public virtual ICollection<SaleLREntry> SaleLREntries { get; set; }
    }
}
