//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RT.DL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerContactInfo
    {
        public int CustomerContactInfoId { get; set; }
        public Nullable<int> fkCustomerId { get; set; }
        public Nullable<int> fkCityId { get; set; }
        public string OfficePhone { get; set; }
        public string Fax { get; set; }
        public string Email { get; set; }
        public string SMSName { get; set; }
        public string SMSCellNumber { get; set; }
        public string RemContactPerson { get; set; }
        public string RemContactPhone { get; set; }
        public string RemSMSCell1 { get; set; }
        public string RemSMSCell2 { get; set; }
        public string Address { get; set; }
        public string STDCode { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual MstCity MstCity { get; set; }
    }
}
