//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RT.DL
{
    using System;
    using System.Collections.Generic;
    
    public partial class DiscountEntry
    {
        public int DiscountId { get; set; }
        public string RefType { get; set; }
        public string RefNumber { get; set; }
        public Nullable<System.DateTime> RefDate { get; set; }
        public Nullable<decimal> RefAmount { get; set; }
        public Nullable<int> fkCustomerId { get; set; }
        public Nullable<int> fkSupplierId { get; set; }
        public Nullable<decimal> DiscountAmount { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
        public Nullable<System.DateTime> DiscountDate { get; set; }
        public string Source { get; set; }
        public Nullable<decimal> AdjustedAmount { get; set; }
        public string Narration { get; set; }
        public string Remarks { get; set; }
        public string DiscountDocNo { get; set; }
        public Nullable<bool> IsLocked { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Supplier Supplier { get; set; }
    }
}
