//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RT.DL
{
    using System;
    using System.Collections.Generic;
    
    public partial class FinalBill
    {
        public FinalBill()
        {
            this.FinalBillDetails = new HashSet<FinalBillDetail>();
        }
    
        public int FBillId { get; set; }
        public Nullable<System.DateTime> BillDate { get; set; }
        public string BillType { get; set; }
        public string BillMemo { get; set; }
        public int fkSupplierId { get; set; }
        public string BillMemoNo { get; set; }
        public Nullable<double> Amout { get; set; }
        public Nullable<double> STaxPer { get; set; }
        public Nullable<double> STAmt { get; set; }
        public Nullable<double> SBPer { get; set; }
        public Nullable<double> SBAmt { get; set; }
        public Nullable<double> ECPer { get; set; }
        public Nullable<double> ECAmt { get; set; }
        public Nullable<double> OtherPer { get; set; }
        public Nullable<double> OtherAmt { get; set; }
        public Nullable<double> RaisedAmt { get; set; }
        public Nullable<double> CreditNoted { get; set; }
        public Nullable<double> TotalAmt { get; set; }
        public string BillDetails { get; set; }
        public string CreatedBy { get; set; }
        public string EditedBy { get; set; }
        public string CreatedDate { get; set; }
        public string EditedDate { get; set; }
    
        public virtual Supplier Supplier { get; set; }
        public virtual ICollection<FinalBillDetail> FinalBillDetails { get; set; }
    }
}
