//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RT.DL
{
    using System;
    using System.Collections.Generic;
    
    public partial class MstBranch
    {
        public MstBranch()
        {
            this.Customers = new HashSet<Customer>();
            this.MstCouriers = new HashSet<MstCourier>();
        }
    
        public int BranchId { get; set; }
        public string BranchName { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    
        public virtual ICollection<Customer> Customers { get; set; }
        public virtual ICollection<MstCourier> MstCouriers { get; set; }
    }
}
