//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RT.DL
{
    using System;
    using System.Collections.Generic;
    
    public partial class MstCity
    {
        public MstCity()
        {
            this.CustomerContactInfoes = new HashSet<CustomerContactInfo>();
            this.MstCouriers = new HashSet<MstCourier>();
            this.MstSubAgents = new HashSet<MstSubAgent>();
            this.MstTransports = new HashSet<MstTransport>();
        }
    
        public int CityId { get; set; }
        public string CityName { get; set; }
        public Nullable<int> fkStateId { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    
        public virtual ICollection<CustomerContactInfo> CustomerContactInfoes { get; set; }
        public virtual ICollection<MstCourier> MstCouriers { get; set; }
        public virtual ICollection<MstSubAgent> MstSubAgents { get; set; }
        public virtual ICollection<MstTransport> MstTransports { get; set; }
        public virtual MstState MstState { get; set; }
    }
}
