//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RT.DL
{
    using System;
    using System.Collections.Generic;
    
    public partial class MstUser
    {
        public int UserId { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string EmailId { get; set; }
        public Nullable<int> fkUserRoleId { get; set; }
        public bool IsDeleted { get; set; }
        public string ContactNumber { get; set; }
        public Nullable<int> fkUserTypeId { get; set; }
        public string FullName { get; set; }
    
        public virtual MstUserRole MstUserRole { get; set; }
        public virtual MstUserType MstUserType { get; set; }
    }
}
