//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RT.DL
{
    using System;
    using System.Collections.Generic;
    
    public partial class MstUserType
    {
        public MstUserType()
        {
            this.MstUsers = new HashSet<MstUser>();
        }
    
        public int UserTypeId { get; set; }
        public string TypeName { get; set; }
        public string TypeDescription { get; set; }
    
        public virtual ICollection<MstUser> MstUsers { get; set; }
    }
}
