//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RT.DL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Party
    {
        public int PartyId { get; set; }
        public Nullable<int> fkReferenceId { get; set; }
        public string PartyName { get; set; }
        public string Nature { get; set; }
        public string SpokenTo { get; set; }
        public Nullable<System.DateTime> SpokenDate { get; set; }
        public string SpokenBy { get; set; }
        public string Remarks { get; set; }
        public Nullable<int> fkCustomerId { get; set; }
    
        public virtual Reference Reference { get; set; }
        public virtual Customer Customer { get; set; }
    }
}
