//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RT.DL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReturnDraftChequeBillDetail
    {
        public int ReturnDraftChequeBillId { get; set; }
        public Nullable<int> fkReturnDraftChequeId { get; set; }
        public string BillNo { get; set; }
        public Nullable<System.DateTime> BillDate { get; set; }
        public Nullable<decimal> BillAmount { get; set; }
    
        public virtual ReturnDraftCheque ReturnDraftCheque { get; set; }
    }
}
