//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RT.DL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SaleLREntry
    {
        public int SaleId { get; set; }
        public Nullable<int> fkSupplierId { get; set; }
        public Nullable<int> fkCustomerId { get; set; }
        public Nullable<int> Quantity { get; set; }
        public string LRNumber { get; set; }
        public Nullable<System.DateTime> LRDate { get; set; }
        public Nullable<int> Transport { get; set; }
        public string BookingUp { get; set; }
        public Nullable<int> NoOfBales { get; set; }
        public string Documents { get; set; }
        public string BillNumber { get; set; }
        public Nullable<System.DateTime> BillDate { get; set; }
        public Nullable<double> BillAmount { get; set; }
        public string Terms { get; set; }
        public Nullable<int> DueDays { get; set; }
        public Nullable<double> SpecialDiscount { get; set; }
        public Nullable<int> SpecialDiscountDays { get; set; }
        public string VideNumber { get; set; }
        public Nullable<System.DateTime> LRReceiveDate { get; set; }
        public string Source { get; set; }
        public string Narration { get; set; }
        public Nullable<bool> IsLocked { get; set; }
        public Nullable<bool> IsCreditLimitSet { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Supplier Supplier { get; set; }
    }
}
