//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RT.DL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SuppCollectionEntryDetail
    {
        public int SuppColEntryDetailId { get; set; }
        public string RefNo { get; set; }
        public string RefType { get; set; }
        public Nullable<System.DateTime> RefDate { get; set; }
        public Nullable<double> RefAmt { get; set; }
        public Nullable<double> AdjustedAmt { get; set; }
        public string Narration { get; set; }
        public Nullable<int> fkSuppColEntryId { get; set; }
    
        public virtual SuppCollectionEntry SuppCollectionEntry { get; set; }
    }
}
