//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RT.DL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SuppCollectionEntry
    {
        public SuppCollectionEntry()
        {
            this.SuppCollectionEntryDetails = new HashSet<SuppCollectionEntryDetail>();
        }
    
        public int SuppCollId { get; set; }
        public Nullable<System.DateTime> CollectionDate { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
        public int fkSupplierId { get; set; }
        public string DDCheque { get; set; }
        public string DDChequeNo { get; set; }
        public Nullable<System.DateTime> DDChequeDate { get; set; }
        public string DrawnOn { get; set; }
        public Nullable<double> CollectionAmt { get; set; }
        public string Remarks { get; set; }
    
        public virtual Supplier Supplier { get; set; }
        public virtual ICollection<SuppCollectionEntryDetail> SuppCollectionEntryDetails { get; set; }
    }
}
