//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RT.DL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SuppDiscount
    {
        public SuppDiscount()
        {
            this.SuppDiscounDetails = new HashSet<SuppDiscounDetail>();
        }
    
        public int SupDiscId { get; set; }
        public Nullable<int> fkSupplierId { get; set; }
        public Nullable<System.DateTime> DiscDate { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
        public Nullable<double> DiscAmt { get; set; }
        public string Remarks { get; set; }
    
        public virtual ICollection<SuppDiscounDetail> SuppDiscounDetails { get; set; }
        public virtual Supplier Supplier { get; set; }
    }
}
