//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RT.DL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SupplierContactInfo
    {
        public int SupplierContactInfoId { get; set; }
        public Nullable<int> fkSupplierId { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string OfficePhone { get; set; }
        public string Fax { get; set; }
        public string Residence { get; set; }
        public string ResidenceCity { get; set; }
        public string ResPhone { get; set; }
        public string Email { get; set; }
        public string SMSName { get; set; }
        public string SMSCellNumber { get; set; }
        public string Pin { get; set; }
        public string ResidencePin { get; set; }
        public string State { get; set; }
        public string ResidenceState { get; set; }
    
        public virtual Supplier Supplier { get; set; }
    }
}
